version: '3.1'
services:
  db:
    image: mysql
    ports:
      - 33066:3306
    volumes:
      - ./.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
